DROP TABLE IF EXISTS `weiboUsers`;
CREATE TABLE `weiboUsers` (
  `id` char(32) NOT NULL,
  `userId` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4072 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `QQUsers`;
CREATE TABLE `QQUsers` (
  `id` char(32) NOT NULL,
  `userId` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4072 DEFAULT CHARSET=utf8;

