#!/bin/sh

#for x in 2016010{0..9} 2016011{0..9} 2016012{0..9} 2016013{0..9}
#for x in 2016020{0..9} 2016021{0..9} 2016022{0..9} 2016023{0..9}
for x in 2016030{0..9} 2016031{0..9} 2016032{0..9} 2016033{0..9}
do
    xz=
    zf=~/../HS/$x.7z

    [ -r "$zf" ] || continue
    [ ! -e "x-minute/$x" ] || continue

    if [ ! -e "tmp/$x" ]; then
        7z x -otmp/ $zf
        xz=y
    fi

    if bin/x-minute tmp/$x > x-minute/$x ; then
        [ -z "$xz" ] || rm -rf tmp/$x
        echo "$x: OK"
    else
        rm -f x-minute/$x
        echo "$x: FAIL"
    fi
done

