#!/bin/sh

X=x-minute

exec 2>>err

for d in 2016010{0..9} 2016011{0..9} 2016012{0..9} 2016013{0..9}
#for d in 2016020{0..9} 2016021{0..9} 2016022{0..9} 2016023{0..9}
do
    [ -r "x4o/$d" ] && continue
    [ -r "$X/$d" ] || continue
    bin/x4 $X/$d |sort -rnk 6 |sname.py >x4o/$d
done

bin/x4 `/bin/ls -1 x-minute/* |tail -5` |sort -rnk 6 |sname.py > x4p/`/bin/ls -1 x-minute |tail -1`.5
bin/x4 `/bin/ls -1 x-minute/* |tail -3` |sort -rnk 6 |sname.py > x4p/`/bin/ls -1 x-minute |tail -1`.3

